# Generated by Django 3.2 on 2024-01-20 22:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0017_animal_call_speed_animal_repeats_animal_seqvar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NestStatus',
            new_name='NestEventCodes',
        ),
        migrations.RenameField(
            model_name='nestevent',
            old_name='status',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='dam',
        ),
        migrations.RemoveField(
            model_name='nest',
            name='sire',
        ),
        migrations.AddField(
            model_name='nest',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nest_location', to='birds.location'),
        ),
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mating_dam', to='birds.animal')),
                ('nest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mating_nest', to='birds.nest')),
                ('sire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mating_sire', to='birds.animal')),
            ],
        ),
    ]
