# Generated by Django 3.2 on 2024-01-20 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0018_auto_20240120_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='current_mating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nest_mating', to='birds.mating'),
        ),
    ]
