# Generated by Django 3.2 on 2024-01-20 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0019_nest_current_mating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nest',
            name='location',
        ),
    ]
