# Generated by Django 3.2 on 2024-01-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0020_remove_nest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nest',
            name='current_mating',
        ),
    ]
