# Generated by Django 3.2 on 2024-01-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0021_remove_nest_current_mating'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='age_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
