# Generated by Django 3.2 on 2024-01-23 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0023_auto_20240122_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_dam', to='birds.animal'),
        ),
        migrations.AddField(
            model_name='egg',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_sire', to='birds.animal'),
        ),
    ]
