# Generated by Django 3.2 on 2024-01-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0024_auto_20240122_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='nest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
