# Generated by Django 3.2 on 2024-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0026_nest_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='lay_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
